# Generated by Django 5.2.14 on 2026-05-20 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Report ID')),
                ('vehicle_model', models.CharField(max_length=255, verbose_name='Vehicle Model')),
                ('year', models.IntegerField(verbose_name='Vehicle Year')),
                ('grade', models.IntegerField(default=100, verbose_name='Inspection Score (0-100)')),
                ('package', models.CharField(max_length=100, verbose_name='Package Plan')),
                ('city', models.CharField(max_length=100, verbose_name='Inspection City')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Inspection Date')),
                ('summary', models.TextField(verbose_name='Inspector Verdict Summary')),
                ('obd_status', models.CharField(default='Clean', max_length=50)),
                ('obd_codes', models.JSONField(blank=True, default=list)),
                ('paint_status', models.CharField(default='Original', max_length=50)),
                ('paint_panels', models.JSONField(blank=True, default=list)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('technician_remarks', models.TextField(blank=True, null=True, verbose_name='Technician Remarks')),
                ('disclaimer', models.TextField(default='This is an official secure document compiled by AutoInspect Network.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Report Status')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Uploaded PDF Report File')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Gallery Images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Customer')),
            ],
            options={
                'verbose_name': 'Inspection Report',
                'verbose_name_plural': 'Inspection Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=20, verbose_name='User Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
