# Generated by Django 5.2.14 on 2026-05-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_inspectionreport_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Walkaround Video Link'),
        ),
    ]
