# Generated by Django 5.2.14 on 2026-05-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_inspectionreport_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='accidental_history',
            field=models.TextField(blank=True, null=True, verbose_name='Accidental History'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='body_structural',
            field=models.TextField(blank=True, null=True, verbose_name='Body & Structural State'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='car_make',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Make'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='engine_gearbox',
            field=models.TextField(blank=True, null=True, verbose_name='Engine/Gearbox Performance'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='obd_errors',
            field=models.TextField(blank=True, null=True, verbose_name='OBD Scan Errors Details'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='odometer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Odometer Reading'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transmission'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='vin_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VIN Number'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='water_logged',
            field=models.TextField(blank=True, null=True, verbose_name='Water Logged Status'),
        ),
    ]
