# Generated by Django 5.2.14 on 2026-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_inspectionreport_accidental_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Booking ID'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine Number'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='insurance_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Insurance Details'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Technician Name'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Variant'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('User', 'User')], default='User', max_length=20, verbose_name='User Role'),
        ),
    ]
