# Generated by Django 5.2.14 on 2026-05-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_inspectionreport_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='header_image',
            field=models.TextField(blank=True, null=True, verbose_name='Header Image'),
        ),
    ]
