# Generated by Django 5.2.14 on 2026-05-22 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_inspectionreport_header_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff'),
        ),
        migrations.AddField(
            model_name='booking',
            name='inspection_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inspection Location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='booking',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode'),
        ),
    ]
