# Generated by Django 5.2.14 on 2026-05-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_area_booking_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='obd_qr_images',
            field=models.JSONField(blank=True, default=list, verbose_name='OBD QR Images'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='other_references',
            field=models.JSONField(blank=True, default=list, verbose_name='Other References Images'),
        ),
    ]
