# Generated by Django 5.2.14 on 2026-05-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_inspectionreport_obd_qr_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted At'),
        ),
        migrations.AddField(
            model_name='booking',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
        migrations.AddField(
            model_name='booking',
            name='inspection_status',
            field=models.CharField(default='Pending Assignment', max_length=50, verbose_name='Inspection Status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reached_location_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reached Location At'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Travel Started At'),
        ),
    ]
