# Generated by Django 5.2.14 on 2026-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_notification_booking_accepted_at_booking_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='obd_pdf',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='OBD PDF Report Link'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='obd_video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='OBD Video Link'),
        ),
    ]
