# Generated by Django 5.2.14 on 2026-06-01 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_inspectionreport_obd_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='inspection_status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Inspection Status'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Booking ID')),
                ('razorpay_order_id', models.CharField(max_length=255, unique=True, verbose_name='Razorpay Order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Payment ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20, verbose_name='Payment Status')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.payment', verbose_name='Payment Reference'),
        ),
    ]
