# Generated by Django 5.2.14 on 2026-06-02 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_booking_id_alter_booking_inspection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assignment_method',
            field=models.CharField(choices=[('Auto Assigned', 'Auto Assigned'), ('Manually Assigned', 'Manually Assigned'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=50, verbose_name='Assignment Method'),
        ),
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking', verbose_name='Booking'),
        ),
    ]
